# Generated by Django 4.2.30 on 2026-05-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_cd68de_idx',
            old_name='chat_messag_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_sender__61a5fc_idx',
            old_name='chat_messag_sender_idx',
        ),
    ]
